# data_settings
data_root_dir: "dataset/syn_1/"
batch_size: 32

# model_settings
z_dim: 8
a_dim: 4
K: 5
codec_type: "single-branch"
reconst_weight: 0.01
regularization_weight: 0.3
kalman_weight: 1
kl_weight: 0
dpn_hidden_size: 128
dpn_num_layers: 2
learn_noise_covariance: false
init_noise_scale: 1
init_transition_reg_weight: 1
init_observation_reg_weight: 0.1
symmetrize_covariance: true

# training_settings
epochs: 300
warmup_epochs: 10
learning_rate: 0.001
learning_rate_decay: 0.9
burn_in: 3
batch_operation: "mean"
sequence_operation: "mean"
scheduler_step: 20
evaluation_mode: "batch-wise"

#plot_settings
scalogram_channels: 0
latent_channels: [0, 1]

# environment_settings
device: "cuda:0"
checkpoint_dir: "checkpoints"
evaluation_interval: 20
project_name: "TSKVAE"
